---

- name: "Enable filebeat module prospectors"
  set_fact:
   filebeat_config_prospectors: "{{ filebeat_config_prospectors }}\n{{ module_filebeat_config_prospectors }}"
  when: nginx is defined

- name: "Enable filebeat json prospectors"
  set_fact:
   filebeat_config_prospectors: "{{ filebeat_config_prospectors }}\n{{ json_filebeat_config_prospectors }}"
  when: json_log_location is defined

- include: filebeat.yml

- name: "Enable nginx filebeat module"
  shell: "filebeat modules enable nginx"
  when: nginx==true

- name: "Copy custom nginx filebeat conf"
  template: src=nginx.yml.j2
            dest=/etc/filebeat/modules.d/nginx.yml
  when: nginx==true

- name: "Restart filebeat"
  service:
     name: filebeat
     state: restarted